version: '3.9'

services:

  yone_wi:
    build: docker/php
    container_name: yone-wi
    image: magidba/yone_wi:1.0
    restart: always
    ports:
      - 8015:80
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    depends_on:
      - phpmyadmin
    networks:
      - reseau_yone_wi

  database:
    image: mysql:8.2
    container_name: mysql_yone_wi
    volumes:
      - volume_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: magidba
      MYSQL_DATABASE: yone_wi
    ports:
      - 8002:3306
    networks:
      - reseau_yone_wi

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-yone_wi
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: magidba
      PMA_HOST: database
    networks:
      - reseau_yone_wi
    depends_on:
      - database

volumes:
  volume_db:
networks:
  reseau_yone_wi:
