<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LigneController;
use App\Http\Controllers\TarifController;
use App\Http\Controllers\ReseauController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\AbonnementController;
use App\Http\Controllers\AdminSystemController;

Route::post("login", [UserController::class, "login"]);
Route::get("profile", [UserController::class, "profile"]);
Route::get("refresh", [UserController::class, "refreshToken"]);
Route::get("logout", [UserController::class, "logout"]);
Route::patch('updateadmin', [AdminSystemController::class, 'update']);
Route::resource('users', UserController::class)->except('edit', 'create', 'show');
Route::get('users/etat/{user}', [UserController::class, "changerEtat"]);
Route::resource('roles', RoleController::class)->except(['show', 'create', 'edit']);
Route::get("roles/restaure/{role}", [RoleController::class, "restore"]);
Route::post('search', [SearchController::class, 'searching']);
Route::apiResource('abonnements', AbonnementController::class);
Route::patch('abonnements/restaurer/{abonnement}', [AbonnementController::class, "restore"]);
Route::get('abonnements/deleted', [AbonnementController::class, 'deleted']);
Route::delete('abonnements/empty-trash', [AbonnementController::class, 'emptyTrash']);
Route::apiResource('lignes', LigneController::class);
Route::patch('lignes/restaurer/{ligne}', [LigneController::class, "restore"]);
Route::get('lignes/deleted', [LigneController::class, 'deleted']);
Route::delete('lignes/empty-trash', [LigneController::class, 'emptyTrash']);
Route::apiResource('reseaus', ReseauController::class);
Route::patch('reseaus/restaurer/{reseau}', [ReseauController::class, "restore"]);
Route::get('reseaus/deleted', [ReseauController::class, 'deleted']);
Route::delete('reseaus/empty-trash', [ReseauController::class, 'emptyTrash']);
Route::apiResource('sections', SectionController::class);
Route::patch('sections/restaurer/{section}', [SectionController::class, "restore"]);
Route::get('sections/deleted', [SectionController::class, 'deleted']);
Route::delete('sections/empty-trash', [SectionController::class, 'emptyTrash']);
Route::apiResource('tarifs', TarifController::class);
Route::patch('tarifs/restaurer/{tarif}', [TarifController::class, "restore"]);
Route::get('tarifs/deleted', [TarifController::class, 'deleted']);
Route::delete('tarifs/empty-trash', [TarifController::class, 'emptyTrash']);
Route::apiResource('types', TypeController::class);
Route::patch('types/restaurer/{type}', [TypeController::class, "restore"]);
Route::get('types/deleted', [TypeController::class, 'deleted']);
Route::delete('types/empty-trash', [TypeController::class, 'emptyTrash']);
