FROM php:8.2-apache

#installation des extensions php
RUN apt-get update && apt-get install -y \
    git zip unzip libpng-dev \
    libzip-dev default-mysql-client
#active les extentions
RUN docker-php-ext-install pdo pdo_mysql zip gd

#installation du module apache pour la reecriture des url
RUN a2enmod rewrite
#cest comme un dossier ou on met des sous fichiers dedant 
WORKDIR /var/www
#ca permet de copier tous les dossier et le mettre dans le www
COPY . /var/www
#donner des droits d'accés pour le dossier storage
RUN chown -R www-data:www-data /var/www/storage


# ajout de composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# On utilise composer ici pour installer les dépendances de notre projet
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --optimize-autoloader --no-dev

#l'image sera accessible sur le port 80 dans le projet
EXPOSE 80

# Copier la configuration Apache personnalisée
COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf
#il execute le continue du fichier docker.sh
ENTRYPOINT [ "bash","./docker/docker.sh" ]
#ca permet d'allumer le server apache
CMD ["apache2-foreground"]