FROM php:8.2-apache
RUN apt-get update && apt-get install -y \
    git zip unzip libpng-dev \
    libzip-dev default-mysql-client
RUN docker-php-ext-install pdo pdo_mysql zip gd
RUN a2enmod rewrite
WORKDIR /var/www/html
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html/storage
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --optimize-autoloader
EXPOSE 80
COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf
ENTRYPOINT [ "bash","./docker/docker.sh" ]
CMD ["apache2-foreground"]